spring:
  application:
    name: orderSystem
  datasource:
    url: jdbc:mysql://localhost:3306/ORDER_SYSTEM_DB?useSSL=false&serverTimezone=UTC
    username: root
    password: ENC(6ATWr+veeOXWM6QwkA8AEP33s6bb9b3EsFa7kSDYG6F1J0xjzwmarG3jOrlNE2XJ)
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  cors:
    # 允许的域名，多个用逗号隔开
    allowed-origins: "http://localhost:5173"
    # 允许的方法
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    # 允许的头信息
    allowed-headers: "*"
    # 暴露给前端的头信息 (比如你的 New-Access-Token)
    exposed-headers: "New-Access-Token"
    # 路径匹配规则
    path-pattern: "/**"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dianchong.ordersystem.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: true

jwt:
  secret: ENC(nRyzXWZYukZptf6izLh8Xsfg4CIdbo8Y/K3zc3gYJfsnJkyY9Qdllhd5ocJ4sIDrJ4jaMn6msl84kltkesKF83KT1m+dcOTqkOl8/AnShZFKjttGXIj5j3RCSWBpJCRA4F55E3Jr4hubb+ztwqD0qA==)
  access-token-validity: 600000 # 过期时间：10分钟 (1000 * 60 * 10)
  refresh-token-validity: 604800000 # 过期时间：7天 (1000 * 60 * 60 * 24 * 7)

jasypt:
  encryptor:
    # 指定 AES-256 算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 【关键】AES 必须配置 IV 生成器
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    # 推荐配置随机盐生成器
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    password: dianchong888 #仅在开发使用的配置,生产环境请通过环境变量或命令行参数传入